### ISSUE TITLE
Giveaway cancelled, no valid participations.

### ISSUE THREAD

**Issue by ghost** [Zaid-maker/dis-giveaway-bot#24]
So i have tried with 4 people to host a giveaway i set the winner to 1 

and had 4 people react to it and after it ended it said

Giveaway cancelled, no valid participations.

then again i tried but this time with 5 people reacting to the giveaway and still the same message posted.

Giveaway cancelled, no valid participations.

**Comment by Zaid-maker** [comment]
the people who participate in the giveaway needs to be active and chat with others and after the giveaway ends it will pick the winner who has most messages.

**Comment by ABotDev** [comment]
if you want that people with admin perms can win. remove 1 line from index.js `exemptPermissions: [ "MANAGE_MESSAGES", "ADMINISTRATOR" ],`
