### ISSUE TITLE
Update package.json to fix all isues and remove database.json.

### ISSUE THREAD

**Issue by ABotDev** [Zaid-maker/dis-giveaway-bot#33]
`{
  "name": "hello-express",
  "version": "1.1.3",
  "description": "A simple Node app built on Express, instantly up and running.",
  "main": "index.js",
  "scripts": {
    "start": "node index.js"
  },
  "dependencies": {
    "beautify": "^0.0.8",
    "dblapi.js": "^2.4.0",
    "discord-giveaways": "^4.1.8",
    "discord.js": "^12.2.0",
    "express": "^4.17.1",
    "moment": "^2.27.0",
    "ms": "^2.1.2",
    "http": "^0.0.0"
  },
  "engines": {
    "node": "12.x"
  },
  "repository": {
    "url": "https://glitch.com/edit/#!/hello-express"
  },
  "license": "MIT",
  "keywords": [
    "node",
    "glitch",
    "express"
  ]
}
`

**Comment by Zaid-maker** [comment]
You should open a PR

**Comment by ABotDev** [comment]
didn't work
so i opened this

**Comment by Zaid-maker** [comment]
Fixed
