### ISSUE TITLE
No Winner when giveaway ends.

### ISSUE THREAD

**Issue by Positive2022** [Zaid-maker/dis-giveaway-bot#48]
When you try the start giveaway command, it works fine. But when giveaway ends it does no announces any winner and says not enough participants :\

**Comment by ABotDev** [comment]
Hello, Do you host the bot yourself?
if so I had this a while ago but it was an issue with the permissions you cant win if you have the permission: `admin`.
I changed the code so you can win if you have admin permission do you want my code?
Do you use the public bot? you need to wait for the code owner to change it.
I can make a pull request to fix this but i can't push it to the public bot. 
- abotdev
- Discord ItsJustNickDev#6969

**Comment by Zaid-maker** [comment]
You can make pull request I will put it to the public bot.

**Comment by ABotDev** [comment]
okay

**Comment by ABotDev** [comment]
You did that already
because i told you 3 months ago
LMAO
- abotdev
- Discord ItsJustNickDev#6969

**Comment by Positive2022** [comment]
Alright. Now i know why i was not winning the giveaways when only im participant 😂

**Comment by itsjustnickdev** [comment]
LMAO
