### ISSUE TITLE
Feature request: add support for running the bot without external database

### ISSUE THREAD

**Issue by GoudronViande24** [Zaid-maker/dis-giveaway-bot#65]
This could be useful for small communities which don't need all the power of MongoDB, or people who need a simpler configuration.

Something like SQLite could be nice.

**Comment by Zaid-maker** [comment]
Ok I will make that feature soon.

**Comment by Zaid-maker** [comment]
@GoudronViande24 
Added: 4ea1a04449db3513c225cbc74c775de44a6eb05d

**Comment by GoudronViande24** [comment]
MySQL is a great database system, and it is very good that it has been added.

One thing is that it still requires an external database server. Maybe add something for very simple installation that don't require an external server? Like SQLite or a "file-based database"?

**Comment by Zaid-maker** [comment]
It's already in the code bro if u look closer in the index file you will
find out that it's using default json database. You can make a PR if u want
to add something.
